### ISSUE TITLE
부정 조건문

### ISSUE THREAD

**Issue by Qwaz** [disjukr/yaksok.js#41]
[부정 조건문](https://docs.google.com/presentation/d/1d3X4r-U-2L2e2UgWLxLgc_CO0Af3RNqMS3qic3t7iAE/edit?pref=2&pli=1#slide=id.g745fa4e400862e4_0)이 아직 구현되지 않았습니다.

```
만약 (조건) 아니면
    "아닙니다" 보여주기
```

**Comment by disjukr** [comment]
https://github.com/disjukr/yaksok.js/blob/master/src%2Fparser.jison#L71
여기 아래 한 줄 추가하면 될 것 같습니다
