### ISSUE TITLE
약속 문서 파싱 자동화하기

### ISSUE THREAD

**Issue by Qwaz** [disjukr/yaksok.js#52]
만들겠다고 하고 자꾸 안 하네요. 26일 이내로 완성하겠습니다.

**Comment by disjukr** [comment]
와와

**Comment by Qwaz** [comment]
package.json의 scripts 부분에 추가해서 `npm run doc` 이렇게 돌릴까 하는데 혹시 다른 제안 있으신가요?

**Comment by disjukr** [comment]
`npm run doc` 좋을 것 같아요.
한가지 더 해야할 것 같은 부분은 `prepublish`에다가
`npm run test && npm run min` 이 부분을
`npm run doc && npm run test && npm run min`로 바꾸면 좋을 듯

**Comment by Qwaz** [comment]
code highlighting은 놀이터 우측 패널을 참고해 ace editor의 read only mode로 구현하겠습니다.
