### ISSUE TITLE
놀이터 기능 작동 중지

### ISSUE THREAD

**Issue by Qwaz** [disjukr/yaksok.js#53]
[놀이터](http://0xabcdef.com/yaksok.js/#play)

크롬 버전 48.0.2564.116 m 기준으로 browser-polyfill.min.js에서 `Unhandled promise rejection TypeError: text.match is not a function`이라는 에러가 발생하며 화면 우측에 파싱된 js 코드가 출력되지 않습니다.

**Comment by disjukr** [comment]
흠... 로컬에서 띄워보면 재현이 안되는데 배포된 링크에서는 거의 매번 재현되네요;; 뭐가 문제지...

**Comment by disjukr** [comment]
fixed from https://github.com/disjukr/yaksok.js/commit/c581011eae7c6e273db6a230f9b6ae4ffb03efb0
